url: https://y7kim.github.io
baseurl: 

# Site settings
title: Minh and Rich
email: rsvp@minhandrich.com
description: "Minh and Rich are getting married"

sass:
  sass_dir:          _scss
  style:            :compressed